<template>
  <div class="page-container brand-page">
    <div class="page-header"><div><h1>前台品牌 Logo</h1><p>查看收银系统和 PC 点播系统正在使用的 Logo 与变更审批状态。</p></div><n-button type="primary" @click="router.push('/shop/brand-settings/apply')">{{ isCustom ? '申请更新 Logo' : '申请替换 Logo' }}</n-button></div>
    <section class="demo-bar"><span>原型状态演示</span><n-space size="small"><n-button v-for="item in demoOptions" :key="item.value" size="small" :type="demoMode === item.value ? 'primary' : 'default'" @click="demoMode = item.value">{{ item.label }}</n-button></n-space></section>
    <n-alert v-if="displayStatus === 'rejected'" type="error" :bordered="false" class="status-alert">上次申请已被驳回：请调整素材后重新提交。</n-alert>
    <section class="logo-grid"><article v-for="item in targets" :key="item.title" class="logo-card"><div class="card-head"><div><h2>{{ item.title }}</h2><p>当前生效版本</p></div><n-tag :type="item.custom ? 'success' : 'default'">{{ item.custom ? '门店 Logo 已生效' : '平台默认 Logo' }}</n-tag></div><div class="logo-stage"><img v-if="item.url" :src="item.url" :alt="item.title + '当前 Logo'" /><div v-else :class="item.custom ? 'merchant-logo' : 'platform-logo'">{{ item.custom ? '福田旗舰店' : '头号空间' }}<small v-if="item.custom">门店 Logo v2</small></div></div><div class="logo-meta"><span>Logo 尺寸</span><strong>800 × 240 px</strong></div></article></section>
    <section v-if="displayStatus === 'pending'" class="content-card pending-card"><div class="section-head"><div><h2>本次申请</h2><p>提交时间：刚刚提交 · 备注：门店春季品牌焕新。审核通过前，前台继续使用上方当前生效版本。</p></div><n-tag type="warning">运营审批中</n-tag></div><div class="logo-grid"><article v-for="item in pendingTargets" :key="item.title" class="pending-preview"><span>{{ item.title }}</span><div class="merchant-logo">福田旗舰店<br /><small>新申请 Logo</small></div></article></div></section>
    <section v-else class="content-card"><div class="section-head"><div><h2>最近变更</h2><p>{{ isCustom ? '当前门店 Logo v2 · 已生效于 2026-09-22 14:30。' : '当前使用平台默认 Logo，尚未提交变更申请。' }}</p></div><n-button secondary @click="router.push('/shop/brand-settings/apply')">{{ isCustom ? '申请更新 Logo' : '申请替换 Logo' }}</n-button></div></section>
  </div>
</template>
<script setup lang="ts">
import { computed, ref } from 'vue'
import { useRouter } from 'vue-router'
import { NAlert, NButton, NSpace, NTag } from 'naive-ui'
type Brand = { status:string; cashierLogoUrl:string; vodLogoUrl:string; effectiveCashierLogoUrl:string; effectiveVodLogoUrl:string; note:string; rejectionReason?:string }
const router=useRouter(); const brand=ref<Brand>({status:'draft',cashierLogoUrl:'',vodLogoUrl:'',effectiveCashierLogoUrl:'',effectiveVodLogoUrl:'',note:'',...(JSON.parse(localStorage.getItem('store-brand-config:hengran')||'{}'))}); const demoMode=ref<'default'|'approved'|'pending'|'rejected'>('default')
const demoOptions=[{value:'default',label:'平台默认'},{value:'approved',label:'已生效'},{value:'pending',label:'审核中'},{value:'rejected',label:'已驳回'}] as const
const displayStatus=computed(()=>demoMode.value); const isCustom=computed(()=>demoMode.value==='approved'||demoMode.value==='pending'||demoMode.value==='rejected')
const targets=computed(()=>[{title:'收银系统',url:demoMode.value==='default'?'':brand.value.effectiveCashierLogoUrl,custom:isCustom.value},{title:'PC 点播系统',url:demoMode.value==='default'?'':brand.value.effectiveVodLogoUrl,custom:isCustom.value}])
const pendingTargets=computed(()=>[{title:'收银系统'},{title:'PC 点播系统'}])
</script>
<style scoped>.brand-page{max-width:1180px;padding:24px}.page-header{display:flex;justify-content:space-between;align-items:flex-start;gap:16px;margin-bottom:18px}.page-header h1{margin:0;font-size:22px}.page-header p,.card-head p,.section-head p{margin:6px 0 0;color:var(--text-muted);font-size:13px}.demo-bar{display:flex;align-items:center;gap:16px;padding:12px 16px;margin-bottom:18px;border:1px solid #dbeafe;border-radius:10px;background:#f8fbff}.demo-bar>span{font-size:13px;font-weight:600;color:#1e3a8a}.status-alert{margin-bottom:18px}.logo-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:18px}.logo-card,.content-card{padding:22px;background:#fff;border:1px solid var(--border-color);border-radius:12px}.card-head,.section-head{display:flex;justify-content:space-between;align-items:flex-start;gap:14px;margin-bottom:18px}.card-head h2,.section-head h2{margin:0;font-size:17px}.logo-stage img,.platform-logo,.merchant-logo{width:100%;height:112px;object-fit:contain;padding:16px;background:#0f172a;border-radius:9px}.platform-logo,.merchant-logo,.empty-logo{display:flex;flex-direction:column;align-items:center;justify-content:center;color:#fff;font-weight:700}.merchant-logo{background:linear-gradient(135deg,#075985,#0f766e)}.merchant-logo small{margin-top:5px;color:#ccfbf1;font-size:12px;font-weight:400}.logo-meta{display:flex;justify-content:space-between;margin-top:14px;color:#64748b;font-size:13px}.logo-meta strong{color:#0f172a}.content-card{margin-top:18px}.pending-preview{padding:14px;border:1px solid #fde68a;border-radius:10px;background:#fffbeb}.pending-preview>span{display:block;margin-bottom:9px;color:#92400e;font-size:13px}@media(max-width:720px){.brand-page{padding:16px}.page-header{flex-direction:column}.demo-bar{align-items:flex-start;flex-direction:column}.logo-grid{grid-template-columns:1fr}}</style>
