<template>
  <div class="page-container brand-page">
    <div class="page-header"><div><h1>前台品牌 Logo</h1><p>收银系统与 PC 点播系统分别替换，作为同一份申请提交运营审核。</p></div><n-tag :type="statusType" round>{{ statusLabel }}</n-tag></div>
    <n-alert :type="statusType" :bordered="false" class="status-alert">{{ statusHint }}</n-alert>
    <section class="logo-grid">
      <article v-for="item in logoTargets" :key="item.key" class="logo-card">
        <div class="card-head"><div><h2>{{ item.title }}</h2><p>要求：PNG / WebP · <strong>800 × 240 px</strong> · 不超过 2 MB</p></div><n-tag size="small" :type="item.formUrl ? 'info' : 'default'">{{ item.formUrl ? '已选择新图' : '未选择新图' }}</n-tag></div>
        <div class="logo-stage"><div class="current-logo"><span>当前生效 Logo</span><img v-if="item.effectiveUrl" :src="item.effectiveUrl" :alt="item.title + '当前 Logo'" /><div v-else class="platform-logo">头号空间</div><small>{{ item.effectiveUrl ? '800 × 240 px' : '平台默认 Logo · 800 × 240 px' }}</small></div><div class="arrow">→</div><div class="current-logo"><span>本次申请 Logo</span><img v-if="item.formUrl" :src="item.formUrl" :alt="item.title + '申请 Logo'" /><div v-else class="empty-logo">上传后预览</div><small>{{ item.formUrl ? '800 × 240 px' : '尚未选择图片' }}</small></div></div>
        <n-upload :default-upload="false" :max="1" accept="image/png,image/webp" :before-upload="file => validateUpload(file, item.key)" @update:file-list="files => readLogo(files, item.key)"><n-button secondary>上传 {{ item.title }} Logo</n-button></n-upload>
      </article>
    </section>
    <section class="content-card"><n-form label-placement="top"><n-form-item label="备注"><n-input v-model:value="form.note" type="textarea" :rows="3" placeholder="填写本次 Logo 替换的原因或补充说明" /></n-form-item><n-space><n-button type="primary" @click="submit">提交审核</n-button><span class="submit-hint">可只替换其中一个系统；两个系统会一并生成同一份审核申请。</span></n-space></n-form></section>
  </div>
</template>
<script setup lang="ts">
import { computed, reactive, ref } from 'vue'
import { NAlert, NButton, NForm, NFormItem, NInput, NSpace, NTag, NUpload, useMessage } from 'naive-ui'
type Key = 'cashierLogoUrl' | 'vodLogoUrl'
type Brand = { status:string; cashierLogoUrl:string; vodLogoUrl:string; effectiveCashierLogoUrl:string; effectiveVodLogoUrl:string; note:string; requestAction?:'replace'|'restore_default'; rejectionReason?:string }
const KEY='store-brand-config:hengran'; const message=useMessage()
const brand=ref<Brand>({status:'draft',cashierLogoUrl:'',vodLogoUrl:'',effectiveCashierLogoUrl:'',effectiveVodLogoUrl:'',note:'',...(JSON.parse(localStorage.getItem(KEY)||'{}'))})
if(brand.value.status==='not_authorized') brand.value.status='draft'; if(brand.value.requestAction==='restore_default'){brand.value.status='draft';brand.value.cashierLogoUrl='';brand.value.vodLogoUrl='';brand.value.note='';brand.value.requestAction='replace';localStorage.setItem(KEY,JSON.stringify(brand.value))}
const form=reactive({cashierLogoUrl:brand.value.cashierLogoUrl,vodLogoUrl:brand.value.vodLogoUrl,note:brand.value.note})
const statusLabel=computed(()=>({draft:'待提交',pending:'运营审批中',approved:'已生效',rejected:'已驳回'}[brand.value.status]||'待提交'))
const statusType=computed(()=>({draft:'info',pending:'warning',approved:'success',rejected:'error'}[brand.value.status]||'info') as any)
const statusHint=computed(()=>brand.value.status==='rejected'?`驳回原因：${brand.value.rejectionReason||'请调整图片后重新提交。'}`:brand.value.status==='approved'?'当前版本已生效；重新上传将创建新的审核申请。':'上传符合尺寸要求的图片后提交，审核通过才会替换前台展示。')
const logoTargets=computed(()=>[{key:'cashierLogoUrl' as Key,title:'收银系统',formUrl:form.cashierLogoUrl,effectiveUrl:brand.value.effectiveCashierLogoUrl},{key:'vodLogoUrl' as Key,title:'PC 点播系统',formUrl:form.vodLogoUrl,effectiveUrl:brand.value.effectiveVodLogoUrl}])
function validateUpload(upload:any,key:Key){const file=upload.file as File;if(!file)return false;if(!['image/png','image/webp'].includes(file.type)){message.error('仅支持 PNG 或 WebP 图片');return false}if(file.size>2*1024*1024){message.error('图片不能超过 2 MB');return false}const image=new Image();image.onload=()=>{if(image.width!==800||image.height!==240){message.error(`${key==='cashierLogoUrl'?'收银系统':'PC 点播系统'} Logo 必须为 800 × 240 px`);form[key]=''};URL.revokeObjectURL(image.src)};image.src=URL.createObjectURL(file);return true}
function readLogo(files:any[],key:Key){const file=files[0]?.file as File|undefined;if(!file)return;const image=new Image();const url=URL.createObjectURL(file);image.onload=()=>{URL.revokeObjectURL(url);if(image.width!==800||image.height!==240)return;const reader=new FileReader();reader.onload=()=>{form[key]=String(reader.result||'')};reader.readAsDataURL(file)};image.src=url}
function submit(){if(!form.cashierLogoUrl&&!form.vodLogoUrl)return message.warning('请至少上传一套符合尺寸要求的 Logo');brand.value={...brand.value,cashierLogoUrl:form.cashierLogoUrl,vodLogoUrl:form.vodLogoUrl,note:form.note.trim(),requestAction:'replace',status:'pending',rejectionReason:''};localStorage.setItem(KEY,JSON.stringify(brand.value));message.success('已提交 Logo 替换申请')}
</script>
<style scoped>.brand-page{max-width:1180px;padding:24px}.page-header{display:flex;justify-content:space-between;align-items:flex-start;gap:16px;margin-bottom:18px}.page-header h1{margin:0;font-size:22px}.page-header p{margin:6px 0 0;color:var(--text-muted);font-size:13px}.status-alert{margin-bottom:18px}.logo-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:18px}.logo-card,.content-card{padding:22px;background:#fff;border:1px solid var(--border-color);border-radius:12px}.card-head{display:flex;justify-content:space-between;gap:12px;margin-bottom:18px}.card-head h2{margin:0;font-size:17px}.card-head p{margin:6px 0 0;color:var(--text-muted);font-size:12px}.logo-stage{display:grid;grid-template-columns:1fr 28px 1fr;align-items:center;gap:10px;margin-bottom:18px}.current-logo span,.current-logo small{display:block;font-size:12px;color:#64748b}.current-logo span{margin-bottom:7px}.current-logo small{margin-top:7px}.current-logo img,.platform-logo,.empty-logo{width:100%;height:90px;object-fit:contain;padding:12px;border-radius:8px;background:#0f172a}.platform-logo,.empty-logo{display:flex;align-items:center;justify-content:center;color:#fff;font-weight:700}.empty-logo{background:#f1f5f9;border:1px dashed #94a3b8;color:#64748b;font-weight:400}.arrow{font-size:20px;color:#94a3b8;text-align:center}.content-card{margin-top:18px}.submit-hint{align-self:center;color:#64748b;font-size:12px}@media(max-width:760px){.brand-page{padding:16px}.logo-grid{grid-template-columns:1fr}.logo-stage{grid-template-columns:1fr;gap:8px}.arrow{transform:rotate(90deg)}}</style>
